spring:
  application:
    name: weather-info-service
  datasource:
    username: ${MYSQL_DATABASE_USER:root}
    password: ${MYSQL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DATABASE_HOST:localhost}:3306/${MYSQL_DATABASE_NAME:weather_info_svc}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: local
weather:
  info:
    openweather:
      app-id: ${OPEN_WEATHER_APP_ID}